// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.35.0
// source: comlink/v1/cluster.proto

package comlinkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterClient interface {
	// Join requests admission to the cluster. The sponsor runs the
	// VoteIn protocol with the supplied joiner identity and addr,
	// then returns the ClusterID and the post-admission cluster
	// membership. Returns an error (codes.FailedPrecondition,
	// codes.PermissionDenied, etc) if VoteIn was rejected.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// StreamSnapshot streams a snapshot of one Substrate's state
	// from the sponsor to the joiner (PLAN §10(c)). Server-
	// streaming so multi-GB snapshots don't have to fit in a
	// single gRPC message.
	//
	// The sponsor calls its local app's Snapshotter.Snapshot() to
	// produce the snapshot bytes + the through-offset, then
	// chunks the bytes for transmission. The joiner accumulates
	// chunks (typically to a temp file in DataDir/snapshots/<conv>/)
	// and calls Snapshotter.Restore once with a Reader over the
	// reassembled file.
	//
	// Exempt from the ClusterID handshake interceptor (a joiner
	// making this call IS already known to the cluster via Join,
	// but the gRPC interceptor is set up at connection time and
	// we keep things uniform — see transport/grpc.
	// ExemptHandshakeMethods).
	StreamSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (Cluster_StreamSnapshotClient, error)
}

type clusterClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterClient(cc grpc.ClientConnInterface) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/comlink.v1.Cluster/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) StreamSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (Cluster_StreamSnapshotClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cluster_ServiceDesc.Streams[0], "/comlink.v1.Cluster/StreamSnapshot", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterStreamSnapshotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cluster_StreamSnapshotClient interface {
	Recv() (*SnapshotChunk, error)
	grpc.ClientStream
}

type clusterStreamSnapshotClient struct {
	grpc.ClientStream
}

func (x *clusterStreamSnapshotClient) Recv() (*SnapshotChunk, error) {
	m := new(SnapshotChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServer is the server API for Cluster service.
// All implementations must embed UnimplementedClusterServer
// for forward compatibility
type ClusterServer interface {
	// Join requests admission to the cluster. The sponsor runs the
	// VoteIn protocol with the supplied joiner identity and addr,
	// then returns the ClusterID and the post-admission cluster
	// membership. Returns an error (codes.FailedPrecondition,
	// codes.PermissionDenied, etc) if VoteIn was rejected.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// StreamSnapshot streams a snapshot of one Substrate's state
	// from the sponsor to the joiner (PLAN §10(c)). Server-
	// streaming so multi-GB snapshots don't have to fit in a
	// single gRPC message.
	//
	// The sponsor calls its local app's Snapshotter.Snapshot() to
	// produce the snapshot bytes + the through-offset, then
	// chunks the bytes for transmission. The joiner accumulates
	// chunks (typically to a temp file in DataDir/snapshots/<conv>/)
	// and calls Snapshotter.Restore once with a Reader over the
	// reassembled file.
	//
	// Exempt from the ClusterID handshake interceptor (a joiner
	// making this call IS already known to the cluster via Join,
	// but the gRPC interceptor is set up at connection time and
	// we keep things uniform — see transport/grpc.
	// ExemptHandshakeMethods).
	StreamSnapshot(*SnapshotRequest, Cluster_StreamSnapshotServer) error
	mustEmbedUnimplementedClusterServer()
}

// UnimplementedClusterServer must be embedded to have forward compatible implementations.
type UnimplementedClusterServer struct {
}

func (UnimplementedClusterServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedClusterServer) StreamSnapshot(*SnapshotRequest, Cluster_StreamSnapshotServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSnapshot not implemented")
}
func (UnimplementedClusterServer) mustEmbedUnimplementedClusterServer() {}

// UnsafeClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServer will
// result in compilation errors.
type UnsafeClusterServer interface {
	mustEmbedUnimplementedClusterServer()
}

func RegisterClusterServer(s grpc.ServiceRegistrar, srv ClusterServer) {
	s.RegisterService(&Cluster_ServiceDesc, srv)
}

func _Cluster_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comlink.v1.Cluster/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_StreamSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterServer).StreamSnapshot(m, &clusterStreamSnapshotServer{stream})
}

type Cluster_StreamSnapshotServer interface {
	Send(*SnapshotChunk) error
	grpc.ServerStream
}

type clusterStreamSnapshotServer struct {
	grpc.ServerStream
}

func (x *clusterStreamSnapshotServer) Send(m *SnapshotChunk) error {
	return x.ServerStream.SendMsg(m)
}

// Cluster_ServiceDesc is the grpc.ServiceDesc for Cluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comlink.v1.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Cluster_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSnapshot",
			Handler:       _Cluster_StreamSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "comlink/v1/cluster.proto",
}
