// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comlink/v1/cluster.proto

// Package comlink.v1 — Cluster admin RPCs.
//
// The Cluster service is registered on the same gRPC server as
// Transport but logically separate: it carries cluster-wide
// bootstrap and observability operations, not per-conversation
// traffic. The Join RPC is the sponsor handshake (PLAN §5(h)):
// a new node that lacks a persisted ClusterID dials a sponsor
// and requests admission. The sponsor MUST first VoteIn the
// joiner via the standard membership protocol; on success it
// returns the ClusterID and the post-admission membership list
// (including the joiner). The joiner installs those locally and
// proceeds as a regular replica.
//
// Join is exempt from the ClusterID handshake interceptor —
// the joiner has no ClusterID to send until Join completes.
// See transport/grpc.ExemptHandshakeMethods.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// joiner is the replica requesting admission.
	Joiner *ReplicaID `protobuf:"bytes,1,opt,name=joiner,proto3" json:"joiner,omitempty"`
	// joiner_addr is the network address peers should use to
	// reach the joiner after admission. Propagated through the
	// VoteIn protocol's MemberAdd commit message so every replica
	// can persist routing information.
	JoinerAddr    string `protobuf:"bytes,2,opt,name=joiner_addr,json=joinerAddr,proto3" json:"joiner_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetJoiner() *ReplicaID {
	if x != nil {
		return x.Joiner
	}
	return nil
}

func (x *JoinRequest) GetJoinerAddr() string {
	if x != nil {
		return x.JoinerAddr
	}
	return ""
}

type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the cluster's ClusterID. The joiner persists
	// it locally and uses it to derive the system conversation ID.
	ClusterId *ClusterID `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// members is the cluster's membership list AFTER the joiner
	// has been admitted (so it includes the joiner).
	Members       []*ClusterMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetClusterId() *ClusterID {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

func (x *JoinResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_comlink_v1_cluster_proto protoreflect.FileDescriptor

const file_comlink_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18comlink/v1/cluster.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"]\n" +
	"\vJoinRequest\x12-\n" +
	"\x06joiner\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06joiner\x12\x1f\n" +
	"\vjoiner_addr\x18\x02 \x01(\tR\n" +
	"joinerAddr\"y\n" +
	"\fJoinResponse\x124\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\v2\x15.comlink.v1.ClusterIDR\tclusterId\x123\n" +
	"\amembers\x18\x02 \x03(\v2\x19.comlink.v1.ClusterMemberR\amembers2D\n" +
	"\aCluster\x129\n" +
	"\x04Join\x12\x17.comlink.v1.JoinRequest\x1a\x18.comlink.v1.JoinResponseBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_cluster_proto_rawDescOnce sync.Once
	file_comlink_v1_cluster_proto_rawDescData []byte
)

func file_comlink_v1_cluster_proto_rawDescGZIP() []byte {
	file_comlink_v1_cluster_proto_rawDescOnce.Do(func() {
		file_comlink_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_cluster_proto_rawDesc), len(file_comlink_v1_cluster_proto_rawDesc)))
	})
	return file_comlink_v1_cluster_proto_rawDescData
}

var file_comlink_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comlink_v1_cluster_proto_goTypes = []any{
	(*JoinRequest)(nil),   // 0: comlink.v1.JoinRequest
	(*JoinResponse)(nil),  // 1: comlink.v1.JoinResponse
	(*ReplicaID)(nil),     // 2: comlink.v1.ReplicaID
	(*ClusterID)(nil),     // 3: comlink.v1.ClusterID
	(*ClusterMember)(nil), // 4: comlink.v1.ClusterMember
}
var file_comlink_v1_cluster_proto_depIdxs = []int32{
	2, // 0: comlink.v1.JoinRequest.joiner:type_name -> comlink.v1.ReplicaID
	3, // 1: comlink.v1.JoinResponse.cluster_id:type_name -> comlink.v1.ClusterID
	4, // 2: comlink.v1.JoinResponse.members:type_name -> comlink.v1.ClusterMember
	0, // 3: comlink.v1.Cluster.Join:input_type -> comlink.v1.JoinRequest
	1, // 4: comlink.v1.Cluster.Join:output_type -> comlink.v1.JoinResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_comlink_v1_cluster_proto_init() }
func file_comlink_v1_cluster_proto_init() {
	if File_comlink_v1_cluster_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_cluster_proto_rawDesc), len(file_comlink_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comlink_v1_cluster_proto_goTypes,
		DependencyIndexes: file_comlink_v1_cluster_proto_depIdxs,
		MessageInfos:      file_comlink_v1_cluster_proto_msgTypes,
	}.Build()
	File_comlink_v1_cluster_proto = out.File
	file_comlink_v1_cluster_proto_goTypes = nil
	file_comlink_v1_cluster_proto_depIdxs = nil
}
