// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: comlink/v1/cluster.proto

// Package comlink.v1 — Cluster admin RPCs.
//
// The Cluster service is registered on the same gRPC server as
// Transport but logically separate: it carries cluster-wide
// bootstrap and observability operations, not per-conversation
// traffic. The Join RPC is the sponsor handshake (PLAN §5(h)):
// a new node that lacks a persisted ClusterID dials a sponsor
// and requests admission. The sponsor MUST first VoteIn the
// joiner via the standard membership protocol; on success it
// returns the ClusterID and the post-admission membership list
// (including the joiner). The joiner installs those locally and
// proceeds as a regular replica.
//
// Join is exempt from the ClusterID handshake interceptor —
// the joiner has no ClusterID to send until Join completes.
// See transport/grpc.ExemptHandshakeMethods.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// joiner is the replica requesting admission.
	Joiner *ReplicaID `protobuf:"bytes,1,opt,name=joiner,proto3" json:"joiner,omitempty"`
	// joiner_addr is the network address peers should use to
	// reach the joiner after admission. Propagated through the
	// VoteIn protocol's MemberAdd commit message so every replica
	// can persist routing information.
	JoinerAddr    string `protobuf:"bytes,2,opt,name=joiner_addr,json=joinerAddr,proto3" json:"joiner_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetJoiner() *ReplicaID {
	if x != nil {
		return x.Joiner
	}
	return nil
}

func (x *JoinRequest) GetJoinerAddr() string {
	if x != nil {
		return x.JoinerAddr
	}
	return ""
}

type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the cluster's ClusterID. The joiner persists
	// it locally and uses it to derive the system conversation ID.
	ClusterId *ClusterID `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// members is the cluster's membership list AFTER the joiner
	// has been admitted (so it includes the joiner).
	Members       []*ClusterMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetClusterId() *ClusterID {
	if x != nil {
		return x.ClusterId
	}
	return nil
}

func (x *JoinResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// SnapshotRequest identifies WHICH substrate the joiner is
// asking for a snapshot of.
type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conversation_id of the substrate whose snapshot is
	// requested. The sponsor must have a Substrate bound to this
	// conv via Cluster.RegisterSnapshotSource (10(d)).
	ConversationId *ConversationID `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// requester is informational — used by the sponsor's logs /
	// metrics to identify who's pulling.
	Requester     *ReplicaID `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotRequest) GetConversationId() *ConversationID {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *SnapshotRequest) GetRequester() *ReplicaID {
	if x != nil {
		return x.Requester
	}
	return nil
}

// SnapshotChunk is one piece of a streamed snapshot.
//
// Wire discipline:
//   - The FIRST chunk MUST have header set (carries through_offset
//     and total_size_hint). Subsequent chunks have header unset.
//   - chunk_index starts at 0 and MUST increment monotonically.
//   - The LAST chunk MUST have last = true.
//   - data may be empty on a chunk if the snapshot is empty
//     (header-only first chunk with last=true).
type SnapshotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *SnapshotHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` // present only on chunk 0
	ChunkIndex    uint64                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotChunk) GetHeader() *SnapshotHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SnapshotChunk) GetChunkIndex() uint64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// SnapshotHeader carries metadata that's only needed once per
// stream — sent inline on the first SnapshotChunk so the
// receiver can stage / size-check from the start.
type SnapshotHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// through_offset: the log offset of the last Apply included
	// in this snapshot. The joiner installs this snapshot as
	// InitialSnapshot.ThroughOffset so its Substrate's apply
	// pump suppresses double-applies.
	ThroughOffset uint64 `protobuf:"varint,1,opt,name=through_offset,json=throughOffset,proto3" json:"through_offset,omitempty"`
	// total_size_bytes hint: the full snapshot's serialized size
	// if known. Zero = unknown / streaming production. Useful for
	// progress reporting.
	TotalSizeBytes uint64 `protobuf:"varint,2,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotHeader) Reset() {
	*x = SnapshotHeader{}
	mi := &file_comlink_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotHeader) ProtoMessage() {}

func (x *SnapshotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotHeader.ProtoReflect.Descriptor instead.
func (*SnapshotHeader) Descriptor() ([]byte, []int) {
	return file_comlink_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotHeader) GetThroughOffset() uint64 {
	if x != nil {
		return x.ThroughOffset
	}
	return 0
}

func (x *SnapshotHeader) GetTotalSizeBytes() uint64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

var File_comlink_v1_cluster_proto protoreflect.FileDescriptor

const file_comlink_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x18comlink/v1/cluster.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"]\n" +
	"\vJoinRequest\x12-\n" +
	"\x06joiner\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06joiner\x12\x1f\n" +
	"\vjoiner_addr\x18\x02 \x01(\tR\n" +
	"joinerAddr\"y\n" +
	"\fJoinResponse\x124\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\v2\x15.comlink.v1.ClusterIDR\tclusterId\x123\n" +
	"\amembers\x18\x02 \x03(\v2\x19.comlink.v1.ClusterMemberR\amembers\"\x8b\x01\n" +
	"\x0fSnapshotRequest\x12C\n" +
	"\x0fconversation_id\x18\x01 \x01(\v2\x1a.comlink.v1.ConversationIDR\x0econversationId\x123\n" +
	"\trequester\x18\x02 \x01(\v2\x15.comlink.v1.ReplicaIDR\trequester\"\x8c\x01\n" +
	"\rSnapshotChunk\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.comlink.v1.SnapshotHeaderR\x06header\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x04R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\"a\n" +
	"\x0eSnapshotHeader\x12%\n" +
	"\x0ethrough_offset\x18\x01 \x01(\x04R\rthroughOffset\x12(\n" +
	"\x10total_size_bytes\x18\x02 \x01(\x04R\x0etotalSizeBytes2\x90\x01\n" +
	"\aCluster\x129\n" +
	"\x04Join\x12\x17.comlink.v1.JoinRequest\x1a\x18.comlink.v1.JoinResponse\x12J\n" +
	"\x0eStreamSnapshot\x12\x1b.comlink.v1.SnapshotRequest\x1a\x19.comlink.v1.SnapshotChunk0\x01BAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_cluster_proto_rawDescOnce sync.Once
	file_comlink_v1_cluster_proto_rawDescData []byte
)

func file_comlink_v1_cluster_proto_rawDescGZIP() []byte {
	file_comlink_v1_cluster_proto_rawDescOnce.Do(func() {
		file_comlink_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_cluster_proto_rawDesc), len(file_comlink_v1_cluster_proto_rawDesc)))
	})
	return file_comlink_v1_cluster_proto_rawDescData
}

var file_comlink_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_comlink_v1_cluster_proto_goTypes = []any{
	(*JoinRequest)(nil),     // 0: comlink.v1.JoinRequest
	(*JoinResponse)(nil),    // 1: comlink.v1.JoinResponse
	(*SnapshotRequest)(nil), // 2: comlink.v1.SnapshotRequest
	(*SnapshotChunk)(nil),   // 3: comlink.v1.SnapshotChunk
	(*SnapshotHeader)(nil),  // 4: comlink.v1.SnapshotHeader
	(*ReplicaID)(nil),       // 5: comlink.v1.ReplicaID
	(*ClusterID)(nil),       // 6: comlink.v1.ClusterID
	(*ClusterMember)(nil),   // 7: comlink.v1.ClusterMember
	(*ConversationID)(nil),  // 8: comlink.v1.ConversationID
}
var file_comlink_v1_cluster_proto_depIdxs = []int32{
	5, // 0: comlink.v1.JoinRequest.joiner:type_name -> comlink.v1.ReplicaID
	6, // 1: comlink.v1.JoinResponse.cluster_id:type_name -> comlink.v1.ClusterID
	7, // 2: comlink.v1.JoinResponse.members:type_name -> comlink.v1.ClusterMember
	8, // 3: comlink.v1.SnapshotRequest.conversation_id:type_name -> comlink.v1.ConversationID
	5, // 4: comlink.v1.SnapshotRequest.requester:type_name -> comlink.v1.ReplicaID
	4, // 5: comlink.v1.SnapshotChunk.header:type_name -> comlink.v1.SnapshotHeader
	0, // 6: comlink.v1.Cluster.Join:input_type -> comlink.v1.JoinRequest
	2, // 7: comlink.v1.Cluster.StreamSnapshot:input_type -> comlink.v1.SnapshotRequest
	1, // 8: comlink.v1.Cluster.Join:output_type -> comlink.v1.JoinResponse
	3, // 9: comlink.v1.Cluster.StreamSnapshot:output_type -> comlink.v1.SnapshotChunk
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_comlink_v1_cluster_proto_init() }
func file_comlink_v1_cluster_proto_init() {
	if File_comlink_v1_cluster_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_cluster_proto_rawDesc), len(file_comlink_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comlink_v1_cluster_proto_goTypes,
		DependencyIndexes: file_comlink_v1_cluster_proto_depIdxs,
		MessageInfos:      file_comlink_v1_cluster_proto_msgTypes,
	}.Build()
	File_comlink_v1_cluster_proto = out.File
	file_comlink_v1_cluster_proto_goTypes = nil
	file_comlink_v1_cluster_proto_depIdxs = nil
}
