// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comlink/v1/comlink.proto

// Package comlink.v1 defines the wire and on-disk format for the comlink
// substrate. Identity types (ConversationID, ReplicaID, MessageID) are
// fixed in Phase 0 and used unchanged across all later phases. The
// Envelope is the framing for any message that flows on the network or
// is stored in the message log; protocol-specific types (e.g. Psync
// payloads in Phase 1) are serialized into Envelope.payload.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConversationID uniquely identifies a Psync conversation. Generated when
// the conversation is first opened and persisted to stable storage so it
// survives restart. Encoded as 16 random bytes (UUID-like) but the format
// is opaque to consumers.
type ConversationID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationID) Reset() {
	*x = ConversationID{}
	mi := &file_comlink_v1_comlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationID) ProtoMessage() {}

func (x *ConversationID) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_comlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationID.ProtoReflect.Descriptor instead.
func (*ConversationID) Descriptor() ([]byte, []int) {
	return file_comlink_v1_comlink_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// ReplicaID uniquely identifies a participant (process / replica) in a
// conversation. Stable across restarts of the same logical replica.
type ReplicaID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaID) Reset() {
	*x = ReplicaID{}
	mi := &file_comlink_v1_comlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaID) ProtoMessage() {}

func (x *ReplicaID) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_comlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaID.ProtoReflect.Descriptor instead.
func (*ReplicaID) Descriptor() ([]byte, []int) {
	return file_comlink_v1_comlink_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaID) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// MessageID is globally unique without coordination: the (replica_id,
// sequence_number) pair is monotonic per replica per conversation, so
// (conversation_id, replica_id, sequence_number) is unique across the
// system.
type MessageID struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId *ConversationID        `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReplicaId      *ReplicaID             `protobuf:"bytes,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageID) Reset() {
	*x = MessageID{}
	mi := &file_comlink_v1_comlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageID) ProtoMessage() {}

func (x *MessageID) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_comlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageID.ProtoReflect.Descriptor instead.
func (*MessageID) Descriptor() ([]byte, []int) {
	return file_comlink_v1_comlink_proto_rawDescGZIP(), []int{2}
}

func (x *MessageID) GetConversationId() *ConversationID {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *MessageID) GetReplicaId() *ReplicaID {
	if x != nil {
		return x.ReplicaId
	}
	return nil
}

func (x *MessageID) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Envelope is the framing for any message that flows on the network or
// is stored in the local MessageLog.
//
// In Phase 0 only the round-trip Hello uses this; predecessors is empty.
// In Phase 1 (Psync), predecessors lists the message IDs that this
// message causally follows (the parents of this node in the context
// graph).
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MessageID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Predecessors  []*MessageID           `protobuf:"bytes,2,rep,name=predecessors,proto3" json:"predecessors,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_comlink_v1_comlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_comlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_comlink_v1_comlink_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetId() *MessageID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Envelope) GetPredecessors() []*MessageID {
	if x != nil {
		return x.Predecessors
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Hello is the Phase 0 round-trip placeholder. Marshaled into
// Envelope.payload for transport tests.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_comlink_v1_comlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_comlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_comlink_v1_comlink_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_comlink_v1_comlink_proto protoreflect.FileDescriptor

const file_comlink_v1_comlink_proto_rawDesc = "" +
	"\n" +
	"\x18comlink/v1/comlink.proto\x12\n" +
	"comlink.v1\"&\n" +
	"\x0eConversationID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"!\n" +
	"\tReplicaID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\xaf\x01\n" +
	"\tMessageID\x12C\n" +
	"\x0fconversation_id\x18\x01 \x01(\v2\x1a.comlink.v1.ConversationIDR\x0econversationId\x124\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\v2\x15.comlink.v1.ReplicaIDR\treplicaId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\"\x86\x01\n" +
	"\bEnvelope\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\x15.comlink.v1.MessageIDR\x02id\x129\n" +
	"\fpredecessors\x18\x02 \x03(\v2\x15.comlink.v1.MessageIDR\fpredecessors\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x1b\n" +
	"\x05Hello\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_comlink_proto_rawDescOnce sync.Once
	file_comlink_v1_comlink_proto_rawDescData []byte
)

func file_comlink_v1_comlink_proto_rawDescGZIP() []byte {
	file_comlink_v1_comlink_proto_rawDescOnce.Do(func() {
		file_comlink_v1_comlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_comlink_proto_rawDesc), len(file_comlink_v1_comlink_proto_rawDesc)))
	})
	return file_comlink_v1_comlink_proto_rawDescData
}

var file_comlink_v1_comlink_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_comlink_v1_comlink_proto_goTypes = []any{
	(*ConversationID)(nil), // 0: comlink.v1.ConversationID
	(*ReplicaID)(nil),      // 1: comlink.v1.ReplicaID
	(*MessageID)(nil),      // 2: comlink.v1.MessageID
	(*Envelope)(nil),       // 3: comlink.v1.Envelope
	(*Hello)(nil),          // 4: comlink.v1.Hello
}
var file_comlink_v1_comlink_proto_depIdxs = []int32{
	0, // 0: comlink.v1.MessageID.conversation_id:type_name -> comlink.v1.ConversationID
	1, // 1: comlink.v1.MessageID.replica_id:type_name -> comlink.v1.ReplicaID
	2, // 2: comlink.v1.Envelope.id:type_name -> comlink.v1.MessageID
	2, // 3: comlink.v1.Envelope.predecessors:type_name -> comlink.v1.MessageID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_comlink_v1_comlink_proto_init() }
func file_comlink_v1_comlink_proto_init() {
	if File_comlink_v1_comlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_comlink_proto_rawDesc), len(file_comlink_v1_comlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comlink_v1_comlink_proto_goTypes,
		DependencyIndexes: file_comlink_v1_comlink_proto_depIdxs,
		MessageInfos:      file_comlink_v1_comlink_proto_msgTypes,
	}.Build()
	File_comlink_v1_comlink_proto = out.File
	file_comlink_v1_comlink_proto_goTypes = nil
	file_comlink_v1_comlink_proto_depIdxs = nil
}
