// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comlink/v1/psync.proto

// Psync-internal types: state persisted via stable.Storage and
// wire-level control messages exchanged between Psync instances
// (lost-message requests, restart messages, etc.). Application
// payloads ride inside Envelope.payload from comlink.proto.
//
// Wire framing: every Psync send onto the transport is a marshaled
// PsyncMessage. The body oneof discriminates between an ordinary
// Envelope (data) and the various control messages.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MaskState is the persisted form of a Psync replica's mask
// (paper §2.3, PLAN §5.2). Persisting on every change keeps the
// recovery path simple in Phase 4 — there's no special "checkpoint
// the mask" step to coordinate, the latest persisted MaskState IS
// the recovery state.
type MaskState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each entry is the bytes of a ReplicaID currently masked out at
	// this replica.
	MaskedReplicas [][]byte `protobuf:"bytes,1,rep,name=masked_replicas,json=maskedReplicas,proto3" json:"masked_replicas,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MaskState) Reset() {
	*x = MaskState{}
	mi := &file_comlink_v1_psync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskState) ProtoMessage() {}

func (x *MaskState) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_psync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskState.ProtoReflect.Descriptor instead.
func (*MaskState) Descriptor() ([]byte, []int) {
	return file_comlink_v1_psync_proto_rawDescGZIP(), []int{0}
}

func (x *MaskState) GetMaskedReplicas() [][]byte {
	if x != nil {
		return x.MaskedReplicas
	}
	return nil
}

// LostMessageRequest asks the receiving replica to retransmit a
// specific (sender, seq) message that the requester needs but does
// not have locally. Per paper §2.3, the requester directs the
// request at the sender of the NEW message that referenced the
// missing predecessor — that sender is guaranteed to have the
// missing message in its own log/graph, even if the missing
// message originated elsewhere (it had to have it as a predecessor
// of its own send).
type LostMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sender whose message we're missing (NOT the peer we're
	// asking; the message we want is from missing_sender at
	// missing_seq).
	MissingSender *ReplicaID `protobuf:"bytes,1,opt,name=missing_sender,json=missingSender,proto3" json:"missing_sender,omitempty"`
	MissingSeq    uint64     `protobuf:"varint,2,opt,name=missing_seq,json=missingSeq,proto3" json:"missing_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LostMessageRequest) Reset() {
	*x = LostMessageRequest{}
	mi := &file_comlink_v1_psync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostMessageRequest) ProtoMessage() {}

func (x *LostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_psync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostMessageRequest.ProtoReflect.Descriptor instead.
func (*LostMessageRequest) Descriptor() ([]byte, []int) {
	return file_comlink_v1_psync_proto_rawDescGZIP(), []int{1}
}

func (x *LostMessageRequest) GetMissingSender() *ReplicaID {
	if x != nil {
		return x.MissingSender
	}
	return nil
}

func (x *LostMessageRequest) GetMissingSeq() uint64 {
	if x != nil {
		return x.MissingSeq
	}
	return 0
}

// PsyncMessage is the outer wrapper for every byte payload Psync
// hands to the transport. Receivers unmarshal PsyncMessage, dispatch
// on the body oneof. Phase 1 ships envelope + lost_message_request;
// Phase 1(g) will extend with restart_message and restart_ack.
type PsyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*PsyncMessage_Envelope
	//	*PsyncMessage_LostMessageRequest
	Body          isPsyncMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsyncMessage) Reset() {
	*x = PsyncMessage{}
	mi := &file_comlink_v1_psync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsyncMessage) ProtoMessage() {}

func (x *PsyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_psync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsyncMessage.ProtoReflect.Descriptor instead.
func (*PsyncMessage) Descriptor() ([]byte, []int) {
	return file_comlink_v1_psync_proto_rawDescGZIP(), []int{2}
}

func (x *PsyncMessage) GetBody() isPsyncMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PsyncMessage) GetEnvelope() *Envelope {
	if x != nil {
		if x, ok := x.Body.(*PsyncMessage_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

func (x *PsyncMessage) GetLostMessageRequest() *LostMessageRequest {
	if x != nil {
		if x, ok := x.Body.(*PsyncMessage_LostMessageRequest); ok {
			return x.LostMessageRequest
		}
	}
	return nil
}

type isPsyncMessage_Body interface {
	isPsyncMessage_Body()
}

type PsyncMessage_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3,oneof"`
}

type PsyncMessage_LostMessageRequest struct {
	LostMessageRequest *LostMessageRequest `protobuf:"bytes,2,opt,name=lost_message_request,json=lostMessageRequest,proto3,oneof"`
}

func (*PsyncMessage_Envelope) isPsyncMessage_Body() {}

func (*PsyncMessage_LostMessageRequest) isPsyncMessage_Body() {}

var File_comlink_v1_psync_proto protoreflect.FileDescriptor

const file_comlink_v1_psync_proto_rawDesc = "" +
	"\n" +
	"\x16comlink/v1/psync.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"4\n" +
	"\tMaskState\x12'\n" +
	"\x0fmasked_replicas\x18\x01 \x03(\fR\x0emaskedReplicas\"s\n" +
	"\x12LostMessageRequest\x12<\n" +
	"\x0emissing_sender\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\rmissingSender\x12\x1f\n" +
	"\vmissing_seq\x18\x02 \x01(\x04R\n" +
	"missingSeq\"\x9e\x01\n" +
	"\fPsyncMessage\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x14.comlink.v1.EnvelopeH\x00R\benvelope\x12R\n" +
	"\x14lost_message_request\x18\x02 \x01(\v2\x1e.comlink.v1.LostMessageRequestH\x00R\x12lostMessageRequestB\x06\n" +
	"\x04bodyBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_psync_proto_rawDescOnce sync.Once
	file_comlink_v1_psync_proto_rawDescData []byte
)

func file_comlink_v1_psync_proto_rawDescGZIP() []byte {
	file_comlink_v1_psync_proto_rawDescOnce.Do(func() {
		file_comlink_v1_psync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_psync_proto_rawDesc), len(file_comlink_v1_psync_proto_rawDesc)))
	})
	return file_comlink_v1_psync_proto_rawDescData
}

var file_comlink_v1_psync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_comlink_v1_psync_proto_goTypes = []any{
	(*MaskState)(nil),          // 0: comlink.v1.MaskState
	(*LostMessageRequest)(nil), // 1: comlink.v1.LostMessageRequest
	(*PsyncMessage)(nil),       // 2: comlink.v1.PsyncMessage
	(*ReplicaID)(nil),          // 3: comlink.v1.ReplicaID
	(*Envelope)(nil),           // 4: comlink.v1.Envelope
}
var file_comlink_v1_psync_proto_depIdxs = []int32{
	3, // 0: comlink.v1.LostMessageRequest.missing_sender:type_name -> comlink.v1.ReplicaID
	4, // 1: comlink.v1.PsyncMessage.envelope:type_name -> comlink.v1.Envelope
	1, // 2: comlink.v1.PsyncMessage.lost_message_request:type_name -> comlink.v1.LostMessageRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_comlink_v1_psync_proto_init() }
func file_comlink_v1_psync_proto_init() {
	if File_comlink_v1_psync_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	file_comlink_v1_psync_proto_msgTypes[2].OneofWrappers = []any{
		(*PsyncMessage_Envelope)(nil),
		(*PsyncMessage_LostMessageRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_psync_proto_rawDesc), len(file_comlink_v1_psync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comlink_v1_psync_proto_goTypes,
		DependencyIndexes: file_comlink_v1_psync_proto_depIdxs,
		MessageInfos:      file_comlink_v1_psync_proto_msgTypes,
	}.Build()
	File_comlink_v1_psync_proto = out.File
	file_comlink_v1_psync_proto_goTypes = nil
	file_comlink_v1_psync_proto_depIdxs = nil
}
