// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comlink/v1/substrate.proto

// Substrate-level wire types: the per-message wrapper that Phase 3+
// puts inside Envelope.payload to multiplex application data with
// failure-detection and membership-protocol control events.
//
// Layering:
//   PsyncMessage { Envelope | LostMessageRequest | Restart* }   <- transport wrapper
//     Envelope.payload -> ConvFrame                             <- this file
//                         ConvFrame.body { app | heartbeat | membership }
//
// Apps that use the membership.Manager API see only the unwrapped
// app bytes; the Manager wraps/unwraps ConvFrame transparently.
// FailureDetection / Membership emit their own ConvFrame variants
// directly and rely on the Manager's frame routing on receive.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConvFrame is the per-Envelope payload discriminator that
// distinguishes application data from substrate control messages.
type ConvFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConvFrame_App
	//	*ConvFrame_Heartbeat
	//	*ConvFrame_Membership
	Body          isConvFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvFrame) Reset() {
	*x = ConvFrame{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvFrame) ProtoMessage() {}

func (x *ConvFrame) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvFrame.ProtoReflect.Descriptor instead.
func (*ConvFrame) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{0}
}

func (x *ConvFrame) GetBody() isConvFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConvFrame) GetApp() []byte {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_App); ok {
			return x.App
		}
	}
	return nil
}

func (x *ConvFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConvFrame) GetMembership() *MembershipEvent {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_Membership); ok {
			return x.Membership
		}
	}
	return nil
}

type isConvFrame_Body interface {
	isConvFrame_Body()
}

type ConvFrame_App struct {
	App []byte `protobuf:"bytes,1,opt,name=app,proto3,oneof"`
}

type ConvFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ConvFrame_Membership struct {
	Membership *MembershipEvent `protobuf:"bytes,3,opt,name=membership,proto3,oneof"`
}

func (*ConvFrame_App) isConvFrame_Body() {}

func (*ConvFrame_Heartbeat) isConvFrame_Body() {}

func (*ConvFrame_Membership) isConvFrame_Body() {}

// Heartbeat is a content-free dummy message emitted by
// FailureDetection when the conversation has been quiet for the
// failure-detection interval. Per paper §4 it serves a dual
// purpose: liveness signal AND ack acceleration (its vector clock
// advances stability detection for messages it depends on).
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{1}
}

// MembershipEvent carries one of the five membership-protocol
// control messages from paper §4.2:
//
//	suspect_down  = (p is down) — FailureDetection suspects p
//	suspect_ack   = (Ack, p is down) — confirms p has stopped
//	suspect_nack  = (Nack, p is down) — refutes the suspicion
//	recovering    = (p is up) — p has restarted and is rejoining
//	recovery_ack  = (Ack, p is up) — confirms incorporation
type MembershipEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MembershipEvent_SuspectDown
	//	*MembershipEvent_SuspectAck
	//	*MembershipEvent_SuspectNack
	//	*MembershipEvent_Recovering
	//	*MembershipEvent_RecoveryAck
	Event         isMembershipEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipEvent) Reset() {
	*x = MembershipEvent{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipEvent) ProtoMessage() {}

func (x *MembershipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipEvent.ProtoReflect.Descriptor instead.
func (*MembershipEvent) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{2}
}

func (x *MembershipEvent) GetEvent() isMembershipEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MembershipEvent) GetSuspectDown() *SuspectDown {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_SuspectDown); ok {
			return x.SuspectDown
		}
	}
	return nil
}

func (x *MembershipEvent) GetSuspectAck() *SuspectAck {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_SuspectAck); ok {
			return x.SuspectAck
		}
	}
	return nil
}

func (x *MembershipEvent) GetSuspectNack() *SuspectNack {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_SuspectNack); ok {
			return x.SuspectNack
		}
	}
	return nil
}

func (x *MembershipEvent) GetRecovering() *Recovering {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_Recovering); ok {
			return x.Recovering
		}
	}
	return nil
}

func (x *MembershipEvent) GetRecoveryAck() *RecoveryAck {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_RecoveryAck); ok {
			return x.RecoveryAck
		}
	}
	return nil
}

type isMembershipEvent_Event interface {
	isMembershipEvent_Event()
}

type MembershipEvent_SuspectDown struct {
	SuspectDown *SuspectDown `protobuf:"bytes,1,opt,name=suspect_down,json=suspectDown,proto3,oneof"`
}

type MembershipEvent_SuspectAck struct {
	SuspectAck *SuspectAck `protobuf:"bytes,2,opt,name=suspect_ack,json=suspectAck,proto3,oneof"`
}

type MembershipEvent_SuspectNack struct {
	SuspectNack *SuspectNack `protobuf:"bytes,3,opt,name=suspect_nack,json=suspectNack,proto3,oneof"`
}

type MembershipEvent_Recovering struct {
	Recovering *Recovering `protobuf:"bytes,4,opt,name=recovering,proto3,oneof"`
}

type MembershipEvent_RecoveryAck struct {
	RecoveryAck *RecoveryAck `protobuf:"bytes,5,opt,name=recovery_ack,json=recoveryAck,proto3,oneof"`
}

func (*MembershipEvent_SuspectDown) isMembershipEvent_Event() {}

func (*MembershipEvent_SuspectAck) isMembershipEvent_Event() {}

func (*MembershipEvent_SuspectNack) isMembershipEvent_Event() {}

func (*MembershipEvent_Recovering) isMembershipEvent_Event() {}

func (*MembershipEvent_RecoveryAck) isMembershipEvent_Event() {}

// SuspectDown announces the sender suspects `suspect` has failed.
// Paper §4.2: emitted by FailureDetection when no message has been
// received from the suspect within the suspicion interval.
type SuspectDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suspect       *ReplicaID             `protobuf:"bytes,1,opt,name=suspect,proto3" json:"suspect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspectDown) Reset() {
	*x = SuspectDown{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspectDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectDown) ProtoMessage() {}

func (x *SuspectDown) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectDown.ProtoReflect.Descriptor instead.
func (*SuspectDown) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{3}
}

func (x *SuspectDown) GetSuspect() *ReplicaID {
	if x != nil {
		return x.Suspect
	}
	return nil
}

// SuspectAck confirms the sender has not received any message from
// `suspect` at the same logical time as the (p is down) message
// for `suspect`. Paper §4.2.3.
type SuspectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suspect       *ReplicaID             `protobuf:"bytes,1,opt,name=suspect,proto3" json:"suspect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspectAck) Reset() {
	*x = SuspectAck{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectAck) ProtoMessage() {}

func (x *SuspectAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectAck.ProtoReflect.Descriptor instead.
func (*SuspectAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{4}
}

func (x *SuspectAck) GetSuspect() *ReplicaID {
	if x != nil {
		return x.Suspect
	}
	return nil
}

// SuspectNack refutes the suspicion: the sender HAS received a
// message from `suspect` at the same logical time as the
// (p is down) message — evidence the suspect is still alive.
// Paper §4.2.3.
type SuspectNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suspect       *ReplicaID             `protobuf:"bytes,1,opt,name=suspect,proto3" json:"suspect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspectNack) Reset() {
	*x = SuspectNack{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspectNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectNack) ProtoMessage() {}

func (x *SuspectNack) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectNack.ProtoReflect.Descriptor instead.
func (*SuspectNack) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{5}
}

func (x *SuspectNack) GetSuspect() *ReplicaID {
	if x != nil {
		return x.Suspect
	}
	return nil
}

// Recovering announces that the sender (`who`) has restarted and is
// rejoining the conversation. Paper §5.2.
type Recovering struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Who           *ReplicaID             `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recovering) Reset() {
	*x = Recovering{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recovering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recovering) ProtoMessage() {}

func (x *Recovering) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recovering.ProtoReflect.Descriptor instead.
func (*Recovering) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{6}
}

func (x *Recovering) GetWho() *ReplicaID {
	if x != nil {
		return x.Who
	}
	return nil
}

// RecoveryAck confirms incorporation of `who` back into the
// membership list. Paper §4.2.3, §5.2: every alive process sends
// (Ack, p is up) before incorporating the recovering process.
type RecoveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Who           *ReplicaID             `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryAck) Reset() {
	*x = RecoveryAck{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryAck) ProtoMessage() {}

func (x *RecoveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryAck.ProtoReflect.Descriptor instead.
func (*RecoveryAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{7}
}

func (x *RecoveryAck) GetWho() *ReplicaID {
	if x != nil {
		return x.Who
	}
	return nil
}

var File_comlink_v1_substrate_proto protoreflect.FileDescriptor

const file_comlink_v1_substrate_proto_rawDesc = "" +
	"\n" +
	"\x1acomlink/v1/substrate.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"\x9d\x01\n" +
	"\tConvFrame\x12\x12\n" +
	"\x03app\x18\x01 \x01(\fH\x00R\x03app\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.comlink.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\n" +
	"membership\x18\x03 \x01(\v2\x1b.comlink.v1.MembershipEventH\x00R\n" +
	"membershipB\x06\n" +
	"\x04body\"\v\n" +
	"\tHeartbeat\"\xc9\x02\n" +
	"\x0fMembershipEvent\x12<\n" +
	"\fsuspect_down\x18\x01 \x01(\v2\x17.comlink.v1.SuspectDownH\x00R\vsuspectDown\x129\n" +
	"\vsuspect_ack\x18\x02 \x01(\v2\x16.comlink.v1.SuspectAckH\x00R\n" +
	"suspectAck\x12<\n" +
	"\fsuspect_nack\x18\x03 \x01(\v2\x17.comlink.v1.SuspectNackH\x00R\vsuspectNack\x128\n" +
	"\n" +
	"recovering\x18\x04 \x01(\v2\x16.comlink.v1.RecoveringH\x00R\n" +
	"recovering\x12<\n" +
	"\frecovery_ack\x18\x05 \x01(\v2\x17.comlink.v1.RecoveryAckH\x00R\vrecoveryAckB\a\n" +
	"\x05event\">\n" +
	"\vSuspectDown\x12/\n" +
	"\asuspect\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\asuspect\"=\n" +
	"\n" +
	"SuspectAck\x12/\n" +
	"\asuspect\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\asuspect\">\n" +
	"\vSuspectNack\x12/\n" +
	"\asuspect\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\asuspect\"5\n" +
	"\n" +
	"Recovering\x12'\n" +
	"\x03who\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x03who\"6\n" +
	"\vRecoveryAck\x12'\n" +
	"\x03who\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x03whoBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_substrate_proto_rawDescOnce sync.Once
	file_comlink_v1_substrate_proto_rawDescData []byte
)

func file_comlink_v1_substrate_proto_rawDescGZIP() []byte {
	file_comlink_v1_substrate_proto_rawDescOnce.Do(func() {
		file_comlink_v1_substrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_substrate_proto_rawDesc), len(file_comlink_v1_substrate_proto_rawDesc)))
	})
	return file_comlink_v1_substrate_proto_rawDescData
}

var file_comlink_v1_substrate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_comlink_v1_substrate_proto_goTypes = []any{
	(*ConvFrame)(nil),       // 0: comlink.v1.ConvFrame
	(*Heartbeat)(nil),       // 1: comlink.v1.Heartbeat
	(*MembershipEvent)(nil), // 2: comlink.v1.MembershipEvent
	(*SuspectDown)(nil),     // 3: comlink.v1.SuspectDown
	(*SuspectAck)(nil),      // 4: comlink.v1.SuspectAck
	(*SuspectNack)(nil),     // 5: comlink.v1.SuspectNack
	(*Recovering)(nil),      // 6: comlink.v1.Recovering
	(*RecoveryAck)(nil),     // 7: comlink.v1.RecoveryAck
	(*ReplicaID)(nil),       // 8: comlink.v1.ReplicaID
}
var file_comlink_v1_substrate_proto_depIdxs = []int32{
	1,  // 0: comlink.v1.ConvFrame.heartbeat:type_name -> comlink.v1.Heartbeat
	2,  // 1: comlink.v1.ConvFrame.membership:type_name -> comlink.v1.MembershipEvent
	3,  // 2: comlink.v1.MembershipEvent.suspect_down:type_name -> comlink.v1.SuspectDown
	4,  // 3: comlink.v1.MembershipEvent.suspect_ack:type_name -> comlink.v1.SuspectAck
	5,  // 4: comlink.v1.MembershipEvent.suspect_nack:type_name -> comlink.v1.SuspectNack
	6,  // 5: comlink.v1.MembershipEvent.recovering:type_name -> comlink.v1.Recovering
	7,  // 6: comlink.v1.MembershipEvent.recovery_ack:type_name -> comlink.v1.RecoveryAck
	8,  // 7: comlink.v1.SuspectDown.suspect:type_name -> comlink.v1.ReplicaID
	8,  // 8: comlink.v1.SuspectAck.suspect:type_name -> comlink.v1.ReplicaID
	8,  // 9: comlink.v1.SuspectNack.suspect:type_name -> comlink.v1.ReplicaID
	8,  // 10: comlink.v1.Recovering.who:type_name -> comlink.v1.ReplicaID
	8,  // 11: comlink.v1.RecoveryAck.who:type_name -> comlink.v1.ReplicaID
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_comlink_v1_substrate_proto_init() }
func file_comlink_v1_substrate_proto_init() {
	if File_comlink_v1_substrate_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	file_comlink_v1_substrate_proto_msgTypes[0].OneofWrappers = []any{
		(*ConvFrame_App)(nil),
		(*ConvFrame_Heartbeat)(nil),
		(*ConvFrame_Membership)(nil),
	}
	file_comlink_v1_substrate_proto_msgTypes[2].OneofWrappers = []any{
		(*MembershipEvent_SuspectDown)(nil),
		(*MembershipEvent_SuspectAck)(nil),
		(*MembershipEvent_SuspectNack)(nil),
		(*MembershipEvent_Recovering)(nil),
		(*MembershipEvent_RecoveryAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_substrate_proto_rawDesc), len(file_comlink_v1_substrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comlink_v1_substrate_proto_goTypes,
		DependencyIndexes: file_comlink_v1_substrate_proto_depIdxs,
		MessageInfos:      file_comlink_v1_substrate_proto_msgTypes,
	}.Build()
	File_comlink_v1_substrate_proto = out.File
	file_comlink_v1_substrate_proto_goTypes = nil
	file_comlink_v1_substrate_proto_depIdxs = nil
}
