// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: comlink/v1/substrate.proto

// Substrate-level wire types: the per-message wrapper that Phase 3+
// puts inside Envelope.payload to multiplex application data with
// failure-detection and membership-protocol control events.
//
// Layering:
//   PsyncMessage { Envelope | LostMessageRequest | Restart* }   <- transport wrapper
//     Envelope.payload -> ConvFrame                             <- this file
//                         ConvFrame.body { app | heartbeat | membership }
//
// Apps that use the membership.Manager API see only the unwrapped
// app bytes; the Manager wraps/unwraps ConvFrame transparently.
// FailureDetection / Membership emit their own ConvFrame variants
// directly and rely on the Manager's frame routing on receive.
//
// Membership protocol design split (PLAN §2.13): SuspectDown is
// informational (FYI / mask trigger), and VoteOut/VoteIn are the
// explicit mechanisms for permanent ML mutation. SuspectDown does
// NOT carry an ack/nack response; only VoteOut and VoteIn do.

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConvFrame is the per-Envelope payload discriminator that
// distinguishes application data from substrate control messages.
type ConvFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ConvFrame_App
	//	*ConvFrame_Heartbeat
	//	*ConvFrame_Membership
	Body          isConvFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvFrame) Reset() {
	*x = ConvFrame{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvFrame) ProtoMessage() {}

func (x *ConvFrame) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvFrame.ProtoReflect.Descriptor instead.
func (*ConvFrame) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{0}
}

func (x *ConvFrame) GetBody() isConvFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ConvFrame) GetApp() []byte {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_App); ok {
			return x.App
		}
	}
	return nil
}

func (x *ConvFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConvFrame) GetMembership() *MembershipEvent {
	if x != nil {
		if x, ok := x.Body.(*ConvFrame_Membership); ok {
			return x.Membership
		}
	}
	return nil
}

type isConvFrame_Body interface {
	isConvFrame_Body()
}

type ConvFrame_App struct {
	App []byte `protobuf:"bytes,1,opt,name=app,proto3,oneof"`
}

type ConvFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ConvFrame_Membership struct {
	Membership *MembershipEvent `protobuf:"bytes,3,opt,name=membership,proto3,oneof"`
}

func (*ConvFrame_App) isConvFrame_Body() {}

func (*ConvFrame_Heartbeat) isConvFrame_Body() {}

func (*ConvFrame_Membership) isConvFrame_Body() {}

// Heartbeat is a content-free dummy message emitted by
// FailureDetection when the conversation has been quiet for the
// failure-detection interval. Per paper §4 it serves a dual
// purpose: liveness signal AND ack acceleration (its vector clock
// advances stability detection for messages it depends on).
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{1}
}

// MembershipEvent carries one of the membership-protocol control
// messages.
//
// SuspectDown / Recovering are informational: peers update their
// SuspectDownList state and mask in/out, but do NOT respond.
//
// VoteOut / VoteIn are the explicit mechanisms for permanent ML
// mutation; peers respond with VoteOutAck/Nack or VoteInAck/Nack.
type MembershipEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*MembershipEvent_SuspectDown
	//	*MembershipEvent_Recovering
	//	*MembershipEvent_VoteOut
	//	*MembershipEvent_VoteOutAck
	//	*MembershipEvent_VoteOutNack
	//	*MembershipEvent_VoteIn
	//	*MembershipEvent_VoteInAck
	//	*MembershipEvent_VoteInNack
	//	*MembershipEvent_RecoveryAck
	Event         isMembershipEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipEvent) Reset() {
	*x = MembershipEvent{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipEvent) ProtoMessage() {}

func (x *MembershipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipEvent.ProtoReflect.Descriptor instead.
func (*MembershipEvent) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{2}
}

func (x *MembershipEvent) GetEvent() isMembershipEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *MembershipEvent) GetSuspectDown() *SuspectDown {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_SuspectDown); ok {
			return x.SuspectDown
		}
	}
	return nil
}

func (x *MembershipEvent) GetRecovering() *Recovering {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_Recovering); ok {
			return x.Recovering
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteOut() *VoteOut {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteOut); ok {
			return x.VoteOut
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteOutAck() *VoteOutAck {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteOutAck); ok {
			return x.VoteOutAck
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteOutNack() *VoteOutNack {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteOutNack); ok {
			return x.VoteOutNack
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteIn() *VoteIn {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteIn); ok {
			return x.VoteIn
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteInAck() *VoteInAck {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteInAck); ok {
			return x.VoteInAck
		}
	}
	return nil
}

func (x *MembershipEvent) GetVoteInNack() *VoteInNack {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_VoteInNack); ok {
			return x.VoteInNack
		}
	}
	return nil
}

func (x *MembershipEvent) GetRecoveryAck() *RecoveryAck {
	if x != nil {
		if x, ok := x.Event.(*MembershipEvent_RecoveryAck); ok {
			return x.RecoveryAck
		}
	}
	return nil
}

type isMembershipEvent_Event interface {
	isMembershipEvent_Event()
}

type MembershipEvent_SuspectDown struct {
	SuspectDown *SuspectDown `protobuf:"bytes,1,opt,name=suspect_down,json=suspectDown,proto3,oneof"`
}

type MembershipEvent_Recovering struct {
	Recovering *Recovering `protobuf:"bytes,2,opt,name=recovering,proto3,oneof"`
}

type MembershipEvent_VoteOut struct {
	VoteOut *VoteOut `protobuf:"bytes,3,opt,name=vote_out,json=voteOut,proto3,oneof"`
}

type MembershipEvent_VoteOutAck struct {
	VoteOutAck *VoteOutAck `protobuf:"bytes,4,opt,name=vote_out_ack,json=voteOutAck,proto3,oneof"`
}

type MembershipEvent_VoteOutNack struct {
	VoteOutNack *VoteOutNack `protobuf:"bytes,5,opt,name=vote_out_nack,json=voteOutNack,proto3,oneof"`
}

type MembershipEvent_VoteIn struct {
	VoteIn *VoteIn `protobuf:"bytes,6,opt,name=vote_in,json=voteIn,proto3,oneof"`
}

type MembershipEvent_VoteInAck struct {
	VoteInAck *VoteInAck `protobuf:"bytes,7,opt,name=vote_in_ack,json=voteInAck,proto3,oneof"`
}

type MembershipEvent_VoteInNack struct {
	VoteInNack *VoteInNack `protobuf:"bytes,8,opt,name=vote_in_nack,json=voteInNack,proto3,oneof"`
}

type MembershipEvent_RecoveryAck struct {
	RecoveryAck *RecoveryAck `protobuf:"bytes,9,opt,name=recovery_ack,json=recoveryAck,proto3,oneof"`
}

func (*MembershipEvent_SuspectDown) isMembershipEvent_Event() {}

func (*MembershipEvent_Recovering) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteOut) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteOutAck) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteOutNack) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteIn) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteInAck) isMembershipEvent_Event() {}

func (*MembershipEvent_VoteInNack) isMembershipEvent_Event() {}

func (*MembershipEvent_RecoveryAck) isMembershipEvent_Event() {}

// SuspectDown is informational: the sender's FailureDetector has
// flagged `suspect` as silent. Receivers update their
// SuspectDownList and Maskout(suspect); recovery happens implicitly
// when a subsequent message arrives from suspect (paper §4.2's
// (p is down), reframed per PLAN §2.13).
type SuspectDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suspect       *ReplicaID             `protobuf:"bytes,1,opt,name=suspect,proto3" json:"suspect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspectDown) Reset() {
	*x = SuspectDown{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspectDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectDown) ProtoMessage() {}

func (x *SuspectDown) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectDown.ProtoReflect.Descriptor instead.
func (*SuspectDown) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{3}
}

func (x *SuspectDown) GetSuspect() *ReplicaID {
	if x != nil {
		return x.Suspect
	}
	return nil
}

// Recovering announces that the sender (`who`) has restarted and
// is rejoining the conversation. Paper §5.2's (p is up).
type Recovering struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Who           *ReplicaID             `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recovering) Reset() {
	*x = Recovering{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recovering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recovering) ProtoMessage() {}

func (x *Recovering) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recovering.ProtoReflect.Descriptor instead.
func (*Recovering) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{4}
}

func (x *Recovering) GetWho() *ReplicaID {
	if x != nil {
		return x.Who
	}
	return nil
}

// RecoveryAck confirms `who`'s incorporation back into the
// membership list. Paper §4.2.3.
type RecoveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Who           *ReplicaID             `protobuf:"bytes,1,opt,name=who,proto3" json:"who,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryAck) Reset() {
	*x = RecoveryAck{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryAck) ProtoMessage() {}

func (x *RecoveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryAck.ProtoReflect.Descriptor instead.
func (*RecoveryAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{5}
}

func (x *RecoveryAck) GetWho() *ReplicaID {
	if x != nil {
		return x.Who
	}
	return nil
}

// VoteOut proposes the permanent removal of `target` from the
// membership list. Paper §4.2 / PLAN §2.13.
type VoteOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOut) Reset() {
	*x = VoteOut{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOut) ProtoMessage() {}

func (x *VoteOut) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOut.ProtoReflect.Descriptor instead.
func (*VoteOut) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{6}
}

func (x *VoteOut) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

// VoteOutAck signals the sender agrees with removing `target`:
// they have not received any message from target at or after the
// VoteOut's logical time.
type VoteOutAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOutAck) Reset() {
	*x = VoteOutAck{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOutAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOutAck) ProtoMessage() {}

func (x *VoteOutAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOutAck.ProtoReflect.Descriptor instead.
func (*VoteOutAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{7}
}

func (x *VoteOutAck) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

// VoteOutNack signals the sender disagrees with removing `target`:
// they have evidence target is alive.
type VoteOutNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOutNack) Reset() {
	*x = VoteOutNack{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOutNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOutNack) ProtoMessage() {}

func (x *VoteOutNack) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOutNack.ProtoReflect.Descriptor instead.
func (*VoteOutNack) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{8}
}

func (x *VoteOutNack) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

// VoteIn proposes the permanent addition of `target` to the
// membership list. addr is the network address peers should use to
// reach target (the gRPC transport, for example, needs this to
// open a connection).
type VoteIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteIn) Reset() {
	*x = VoteIn{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteIn) ProtoMessage() {}

func (x *VoteIn) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteIn.ProtoReflect.Descriptor instead.
func (*VoteIn) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{9}
}

func (x *VoteIn) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *VoteIn) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// VoteInAck signals the sender agrees with adding `target`.
type VoteInAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteInAck) Reset() {
	*x = VoteInAck{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteInAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteInAck) ProtoMessage() {}

func (x *VoteInAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteInAck.ProtoReflect.Descriptor instead.
func (*VoteInAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{10}
}

func (x *VoteInAck) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

// VoteInNack signals the sender disagrees with adding `target`
// (e.g. policy violation, conflict).
type VoteInNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *ReplicaID             `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteInNack) Reset() {
	*x = VoteInNack{}
	mi := &file_comlink_v1_substrate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteInNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteInNack) ProtoMessage() {}

func (x *VoteInNack) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_substrate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteInNack.ProtoReflect.Descriptor instead.
func (*VoteInNack) Descriptor() ([]byte, []int) {
	return file_comlink_v1_substrate_proto_rawDescGZIP(), []int{11}
}

func (x *VoteInNack) GetTarget() *ReplicaID {
	if x != nil {
		return x.Target
	}
	return nil
}

var File_comlink_v1_substrate_proto protoreflect.FileDescriptor

const file_comlink_v1_substrate_proto_rawDesc = "" +
	"\n" +
	"\x1acomlink/v1/substrate.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"\x9d\x01\n" +
	"\tConvFrame\x12\x12\n" +
	"\x03app\x18\x01 \x01(\fH\x00R\x03app\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.comlink.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\n" +
	"membership\x18\x03 \x01(\v2\x1b.comlink.v1.MembershipEventH\x00R\n" +
	"membershipB\x06\n" +
	"\x04body\"\v\n" +
	"\tHeartbeat\"\xa1\x04\n" +
	"\x0fMembershipEvent\x12<\n" +
	"\fsuspect_down\x18\x01 \x01(\v2\x17.comlink.v1.SuspectDownH\x00R\vsuspectDown\x128\n" +
	"\n" +
	"recovering\x18\x02 \x01(\v2\x16.comlink.v1.RecoveringH\x00R\n" +
	"recovering\x120\n" +
	"\bvote_out\x18\x03 \x01(\v2\x13.comlink.v1.VoteOutH\x00R\avoteOut\x12:\n" +
	"\fvote_out_ack\x18\x04 \x01(\v2\x16.comlink.v1.VoteOutAckH\x00R\n" +
	"voteOutAck\x12=\n" +
	"\rvote_out_nack\x18\x05 \x01(\v2\x17.comlink.v1.VoteOutNackH\x00R\vvoteOutNack\x12-\n" +
	"\avote_in\x18\x06 \x01(\v2\x12.comlink.v1.VoteInH\x00R\x06voteIn\x127\n" +
	"\vvote_in_ack\x18\a \x01(\v2\x15.comlink.v1.VoteInAckH\x00R\tvoteInAck\x12:\n" +
	"\fvote_in_nack\x18\b \x01(\v2\x16.comlink.v1.VoteInNackH\x00R\n" +
	"voteInNack\x12<\n" +
	"\frecovery_ack\x18\t \x01(\v2\x17.comlink.v1.RecoveryAckH\x00R\vrecoveryAckB\a\n" +
	"\x05event\">\n" +
	"\vSuspectDown\x12/\n" +
	"\asuspect\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\asuspect\"5\n" +
	"\n" +
	"Recovering\x12'\n" +
	"\x03who\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x03who\"6\n" +
	"\vRecoveryAck\x12'\n" +
	"\x03who\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x03who\"8\n" +
	"\aVoteOut\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06target\";\n" +
	"\n" +
	"VoteOutAck\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06target\"<\n" +
	"\vVoteOutNack\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06target\"K\n" +
	"\x06VoteIn\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06target\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\":\n" +
	"\tVoteInAck\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06target\";\n" +
	"\n" +
	"VoteInNack\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x06targetBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_substrate_proto_rawDescOnce sync.Once
	file_comlink_v1_substrate_proto_rawDescData []byte
)

func file_comlink_v1_substrate_proto_rawDescGZIP() []byte {
	file_comlink_v1_substrate_proto_rawDescOnce.Do(func() {
		file_comlink_v1_substrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_substrate_proto_rawDesc), len(file_comlink_v1_substrate_proto_rawDesc)))
	})
	return file_comlink_v1_substrate_proto_rawDescData
}

var file_comlink_v1_substrate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_comlink_v1_substrate_proto_goTypes = []any{
	(*ConvFrame)(nil),       // 0: comlink.v1.ConvFrame
	(*Heartbeat)(nil),       // 1: comlink.v1.Heartbeat
	(*MembershipEvent)(nil), // 2: comlink.v1.MembershipEvent
	(*SuspectDown)(nil),     // 3: comlink.v1.SuspectDown
	(*Recovering)(nil),      // 4: comlink.v1.Recovering
	(*RecoveryAck)(nil),     // 5: comlink.v1.RecoveryAck
	(*VoteOut)(nil),         // 6: comlink.v1.VoteOut
	(*VoteOutAck)(nil),      // 7: comlink.v1.VoteOutAck
	(*VoteOutNack)(nil),     // 8: comlink.v1.VoteOutNack
	(*VoteIn)(nil),          // 9: comlink.v1.VoteIn
	(*VoteInAck)(nil),       // 10: comlink.v1.VoteInAck
	(*VoteInNack)(nil),      // 11: comlink.v1.VoteInNack
	(*ReplicaID)(nil),       // 12: comlink.v1.ReplicaID
}
var file_comlink_v1_substrate_proto_depIdxs = []int32{
	1,  // 0: comlink.v1.ConvFrame.heartbeat:type_name -> comlink.v1.Heartbeat
	2,  // 1: comlink.v1.ConvFrame.membership:type_name -> comlink.v1.MembershipEvent
	3,  // 2: comlink.v1.MembershipEvent.suspect_down:type_name -> comlink.v1.SuspectDown
	4,  // 3: comlink.v1.MembershipEvent.recovering:type_name -> comlink.v1.Recovering
	6,  // 4: comlink.v1.MembershipEvent.vote_out:type_name -> comlink.v1.VoteOut
	7,  // 5: comlink.v1.MembershipEvent.vote_out_ack:type_name -> comlink.v1.VoteOutAck
	8,  // 6: comlink.v1.MembershipEvent.vote_out_nack:type_name -> comlink.v1.VoteOutNack
	9,  // 7: comlink.v1.MembershipEvent.vote_in:type_name -> comlink.v1.VoteIn
	10, // 8: comlink.v1.MembershipEvent.vote_in_ack:type_name -> comlink.v1.VoteInAck
	11, // 9: comlink.v1.MembershipEvent.vote_in_nack:type_name -> comlink.v1.VoteInNack
	5,  // 10: comlink.v1.MembershipEvent.recovery_ack:type_name -> comlink.v1.RecoveryAck
	12, // 11: comlink.v1.SuspectDown.suspect:type_name -> comlink.v1.ReplicaID
	12, // 12: comlink.v1.Recovering.who:type_name -> comlink.v1.ReplicaID
	12, // 13: comlink.v1.RecoveryAck.who:type_name -> comlink.v1.ReplicaID
	12, // 14: comlink.v1.VoteOut.target:type_name -> comlink.v1.ReplicaID
	12, // 15: comlink.v1.VoteOutAck.target:type_name -> comlink.v1.ReplicaID
	12, // 16: comlink.v1.VoteOutNack.target:type_name -> comlink.v1.ReplicaID
	12, // 17: comlink.v1.VoteIn.target:type_name -> comlink.v1.ReplicaID
	12, // 18: comlink.v1.VoteInAck.target:type_name -> comlink.v1.ReplicaID
	12, // 19: comlink.v1.VoteInNack.target:type_name -> comlink.v1.ReplicaID
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_comlink_v1_substrate_proto_init() }
func file_comlink_v1_substrate_proto_init() {
	if File_comlink_v1_substrate_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	file_comlink_v1_substrate_proto_msgTypes[0].OneofWrappers = []any{
		(*ConvFrame_App)(nil),
		(*ConvFrame_Heartbeat)(nil),
		(*ConvFrame_Membership)(nil),
	}
	file_comlink_v1_substrate_proto_msgTypes[2].OneofWrappers = []any{
		(*MembershipEvent_SuspectDown)(nil),
		(*MembershipEvent_Recovering)(nil),
		(*MembershipEvent_VoteOut)(nil),
		(*MembershipEvent_VoteOutAck)(nil),
		(*MembershipEvent_VoteOutNack)(nil),
		(*MembershipEvent_VoteIn)(nil),
		(*MembershipEvent_VoteInAck)(nil),
		(*MembershipEvent_VoteInNack)(nil),
		(*MembershipEvent_RecoveryAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_substrate_proto_rawDesc), len(file_comlink_v1_substrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comlink_v1_substrate_proto_goTypes,
		DependencyIndexes: file_comlink_v1_substrate_proto_depIdxs,
		MessageInfos:      file_comlink_v1_substrate_proto_msgTypes,
	}.Build()
	File_comlink_v1_substrate_proto = out.File
	file_comlink_v1_substrate_proto_goTypes = nil
	file_comlink_v1_substrate_proto_depIdxs = nil
}
