// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: comlink/v1/transport.proto

package comlinkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the wire form for the gRPC transport. The payload is the
// caller's opaque bytes (typically a marshaled Envelope, but the
// transport doesn't interpret it).
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *ReplicaID             `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_comlink_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_comlink_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetFrom() *ReplicaID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MultiplexFrame is the inner wrapper used by transport.Multiplex
// (Phase 5(b)) to host multiple conversations on one underlying
// transport. Multiplex.Send wraps the caller's payload with the
// owning conversation_id; the receiving Multiplex decodes and
// routes the inner payload to the matching per-conversation
// Recv channel. The conversation_id is OPAQUE to the transport —
// we re-use the comlink ConversationID type for type-safety.
type MultiplexFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId *ConversationID        `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MultiplexFrame) Reset() {
	*x = MultiplexFrame{}
	mi := &file_comlink_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplexFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexFrame) ProtoMessage() {}

func (x *MultiplexFrame) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexFrame.ProtoReflect.Descriptor instead.
func (*MultiplexFrame) Descriptor() ([]byte, []int) {
	return file_comlink_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *MultiplexFrame) GetConversationId() *ConversationID {
	if x != nil {
		return x.ConversationId
	}
	return nil
}

func (x *MultiplexFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SendAck is the response to a Frame send. Currently empty; reserved
// for future per-message protocol negotiation.
type SendAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAck) Reset() {
	*x = SendAck{}
	mi := &file_comlink_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAck) ProtoMessage() {}

func (x *SendAck) ProtoReflect() protoreflect.Message {
	mi := &file_comlink_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAck.ProtoReflect.Descriptor instead.
func (*SendAck) Descriptor() ([]byte, []int) {
	return file_comlink_v1_transport_proto_rawDescGZIP(), []int{2}
}

var File_comlink_v1_transport_proto protoreflect.FileDescriptor

const file_comlink_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1acomlink/v1/transport.proto\x12\n" +
	"comlink.v1\x1a\x18comlink/v1/comlink.proto\"L\n" +
	"\x05Frame\x12)\n" +
	"\x04from\x18\x01 \x01(\v2\x15.comlink.v1.ReplicaIDR\x04from\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"o\n" +
	"\x0eMultiplexFrame\x12C\n" +
	"\x0fconversation_id\x18\x01 \x01(\v2\x1a.comlink.v1.ConversationIDR\x0econversationId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\t\n" +
	"\aSendAck2;\n" +
	"\tTransport\x12.\n" +
	"\x04Send\x12\x11.comlink.v1.Frame\x1a\x13.comlink.v1.SendAckBAZ?github.com/mikehelmick/comlink/internal/pb/comlink/v1;comlinkv1b\x06proto3"

var (
	file_comlink_v1_transport_proto_rawDescOnce sync.Once
	file_comlink_v1_transport_proto_rawDescData []byte
)

func file_comlink_v1_transport_proto_rawDescGZIP() []byte {
	file_comlink_v1_transport_proto_rawDescOnce.Do(func() {
		file_comlink_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comlink_v1_transport_proto_rawDesc), len(file_comlink_v1_transport_proto_rawDesc)))
	})
	return file_comlink_v1_transport_proto_rawDescData
}

var file_comlink_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_comlink_v1_transport_proto_goTypes = []any{
	(*Frame)(nil),          // 0: comlink.v1.Frame
	(*MultiplexFrame)(nil), // 1: comlink.v1.MultiplexFrame
	(*SendAck)(nil),        // 2: comlink.v1.SendAck
	(*ReplicaID)(nil),      // 3: comlink.v1.ReplicaID
	(*ConversationID)(nil), // 4: comlink.v1.ConversationID
}
var file_comlink_v1_transport_proto_depIdxs = []int32{
	3, // 0: comlink.v1.Frame.from:type_name -> comlink.v1.ReplicaID
	4, // 1: comlink.v1.MultiplexFrame.conversation_id:type_name -> comlink.v1.ConversationID
	0, // 2: comlink.v1.Transport.Send:input_type -> comlink.v1.Frame
	2, // 3: comlink.v1.Transport.Send:output_type -> comlink.v1.SendAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comlink_v1_transport_proto_init() }
func file_comlink_v1_transport_proto_init() {
	if File_comlink_v1_transport_proto != nil {
		return
	}
	file_comlink_v1_comlink_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comlink_v1_transport_proto_rawDesc), len(file_comlink_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comlink_v1_transport_proto_goTypes,
		DependencyIndexes: file_comlink_v1_transport_proto_depIdxs,
		MessageInfos:      file_comlink_v1_transport_proto_msgTypes,
	}.Build()
	File_comlink_v1_transport_proto = out.File
	file_comlink_v1_transport_proto_goTypes = nil
	file_comlink_v1_transport_proto_depIdxs = nil
}
