// Copyright 2026 the comlink authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: kvstore/v1/kvstore.proto

package kvstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Op identifies the kind of mutation a Command represents.
type Op int32

const (
	Op_OP_UNSPECIFIED Op = 0
	Op_OP_SET         Op = 1
	Op_OP_DELETE      Op = 2
	// OP_ACK is a no-op command used by the application-level
	// proactive-ack loop to advance the sender's vector-clock
	// slot. Apply ignores OP_ACK for state purposes; the
	// value is in the envelope's VC, not in the payload. Only
	// useful for one-sided write traffic, where peers would
	// otherwise advance their slots only via heartbeats and
	// stall the wave gate.
	Op_OP_ACK Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_SET",
		2: "OP_DELETE",
		3: "OP_ACK",
	}
	Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_SET":         1,
		"OP_DELETE":      2,
		"OP_ACK":         3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_kvstore_v1_kvstore_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_kvstore_v1_kvstore_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{0}
}

// Command is the per-write payload submitted via the substrate.
// Encodes either Op_SET (key, value) or Op_DELETE (key).
//
// On the wire this replaces the prior JSON shape
// `{"op":"set","k":"...","v":"..."}` — protobuf is ~3-5x faster
// to encode/decode and the wire format is smaller (no field
// names, varint integers, length-delimited bytes).
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=kvstore.v1.Op" json:"op,omitempty"`
	Key   string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value is bytes (not string) so binary payloads roundtrip
	// cleanly. The public Store API keeps strings for backward
	// compatibility; the conversion to bytes happens at the
	// Set/Apply boundary.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Snapshot is the on-disk + over-wire format for the full
// state. Written by Store.writeSnapshot to state.snap.pb and
// streamed to joiners via the substrate's StreamSnapshot RPC.
//
// Versioning: increment the package (kvstore.v2) when the
// shape changes incompatibly. Restore checks the magic+version
// header below.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest log offset whose Apply is reflected in `entries`.
	ThroughOffset uint64 `protobuf:"varint,1,opt,name=through_offset,json=throughOffset,proto3" json:"through_offset,omitempty"`
	// Full key→value map serialized as a repeated message. Order
	// is unspecified on the wire; readers reconstruct the map.
	Entries       []*SnapshotEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetThroughOffset() uint64 {
	if x != nil {
		return x.ThroughOffset
	}
	return 0
}

func (x *Snapshot) GetEntries() []*SnapshotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SnapshotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEntry) Reset() {
	*x = SnapshotEntry{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntry) ProtoMessage() {}

func (x *SnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntry.ProtoReflect.Descriptor instead.
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// CommandBatch is the unit of work submitted to the substrate.
// EVERY substrate payload is a CommandBatch, even single writes
// (which become a one-element batch). This keeps the Apply
// path uniform and removes the need for a discriminated
// payload type.
//
// Application-level batching amortizes the per-Submit substrate
// roundtrip (one wave-gate completion, two-peer fan-out) across
// many user-visible writes. Under sustained load it can deliver
// a multiplicative throughput win.
type CommandBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandBatch) Reset() {
	*x = CommandBatch{}
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandBatch) ProtoMessage() {}

func (x *CommandBatch) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_v1_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandBatch.ProtoReflect.Descriptor instead.
func (*CommandBatch) Descriptor() ([]byte, []int) {
	return file_kvstore_v1_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *CommandBatch) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_kvstore_v1_kvstore_proto protoreflect.FileDescriptor

const file_kvstore_v1_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x18kvstore/v1/kvstore.proto\x12\n" +
	"kvstore.v1\"Q\n" +
	"\aCommand\x12\x1e\n" +
	"\x02op\x18\x01 \x01(\x0e2\x0e.kvstore.v1.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"f\n" +
	"\bSnapshot\x12%\n" +
	"\x0ethrough_offset\x18\x01 \x01(\x04R\rthroughOffset\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.kvstore.v1.SnapshotEntryR\aentries\"7\n" +
	"\rSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"?\n" +
	"\fCommandBatch\x12/\n" +
	"\bcommands\x18\x01 \x03(\v2\x13.kvstore.v1.CommandR\bcommands*?\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_SET\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02\x12\n" +
	"\n" +
	"\x06OP_ACK\x10\x03BAZ?github.com/mikehelmick/comlink/internal/pb/kvstore/v1;kvstorepbb\x06proto3"

var (
	file_kvstore_v1_kvstore_proto_rawDescOnce sync.Once
	file_kvstore_v1_kvstore_proto_rawDescData []byte
)

func file_kvstore_v1_kvstore_proto_rawDescGZIP() []byte {
	file_kvstore_v1_kvstore_proto_rawDescOnce.Do(func() {
		file_kvstore_v1_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvstore_v1_kvstore_proto_rawDesc), len(file_kvstore_v1_kvstore_proto_rawDesc)))
	})
	return file_kvstore_v1_kvstore_proto_rawDescData
}

var file_kvstore_v1_kvstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvstore_v1_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvstore_v1_kvstore_proto_goTypes = []any{
	(Op)(0),               // 0: kvstore.v1.Op
	(*Command)(nil),       // 1: kvstore.v1.Command
	(*Snapshot)(nil),      // 2: kvstore.v1.Snapshot
	(*SnapshotEntry)(nil), // 3: kvstore.v1.SnapshotEntry
	(*CommandBatch)(nil),  // 4: kvstore.v1.CommandBatch
}
var file_kvstore_v1_kvstore_proto_depIdxs = []int32{
	0, // 0: kvstore.v1.Command.op:type_name -> kvstore.v1.Op
	3, // 1: kvstore.v1.Snapshot.entries:type_name -> kvstore.v1.SnapshotEntry
	1, // 2: kvstore.v1.CommandBatch.commands:type_name -> kvstore.v1.Command
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kvstore_v1_kvstore_proto_init() }
func file_kvstore_v1_kvstore_proto_init() {
	if File_kvstore_v1_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvstore_v1_kvstore_proto_rawDesc), len(file_kvstore_v1_kvstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kvstore_v1_kvstore_proto_goTypes,
		DependencyIndexes: file_kvstore_v1_kvstore_proto_depIdxs,
		EnumInfos:         file_kvstore_v1_kvstore_proto_enumTypes,
		MessageInfos:      file_kvstore_v1_kvstore_proto_msgTypes,
	}.Build()
	File_kvstore_v1_kvstore_proto = out.File
	file_kvstore_v1_kvstore_proto_goTypes = nil
	file_kvstore_v1_kvstore_proto_depIdxs = nil
}
